name = "SeqShuffle"
uuid = "5ea955a8-74dc-49b5-be65-6ee01fc504f7"
authors = ["kchu25 <skchu@wustl.edu> and contributors"]
version = "0.2.2"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DocumenterTools = "0.1.16"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
